package lab.pkg5_paulinaeuceda;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearHeroes = new javax.swing.JDialog();
        tf_nombre = new javax.swing.JTextField();
        tf_planeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sp_nivel = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_descripcion = new javax.swing.JTextField();
        sp_mortal = new javax.swing.JSpinner();
        Mortalidad = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        sp_altura = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jb_villanos = new javax.swing.JButton();
        jb_poder = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_cate = new javax.swing.JTree();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_villanos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_heroe = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jd_carcel = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_libres = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_encarcelados = new javax.swing.JList<>();
        jp_lista = new javax.swing.JPopupMenu();
        jmi_mover = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jp_login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_contraseñaL = new javax.swing.JPasswordField();
        jb_iniciarSesion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jd_crearHeroes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_crearHeroes.getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, 30));
        jd_crearHeroes.getContentPane().add(tf_planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Registrar");
        jd_crearHeroes.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel3.setText("Nombre");
        jd_crearHeroes.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar.png"))); // NOI18N
        jd_crearHeroes.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel8.setText("Planeta de Origen");
        jd_crearHeroes.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Super Poderes");
        jd_crearHeroes.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        sp_nivel.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jd_crearHeroes.getContentPane().add(sp_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 70, 30));

        jLabel11.setText("Nivel de Poder");
        jd_crearHeroes.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel12.setText("Descripcion");
        jd_crearHeroes.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));
        jd_crearHeroes.getContentPane().add(tf_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 170, 30));

        sp_mortal.setModel(new javax.swing.SpinnerListModel(new String[] {"Si", "No"}));
        jd_crearHeroes.getContentPane().add(sp_mortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 70, 30));

        Mortalidad.setText("¿Mortal?");
        jd_crearHeroes.getContentPane().add(Mortalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(15, 0, null, 1));
        jd_crearHeroes.getContentPane().add(sp_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 80, 30));

        jLabel13.setText("Edad");
        jd_crearHeroes.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        sp_altura.setModel(new javax.swing.SpinnerNumberModel(150, 0, null, 1));
        jd_crearHeroes.getContentPane().add(sp_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 80, 30));

        jLabel14.setText("Altura");
        jd_crearHeroes.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButton2.setText("Crear Heroe");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jd_crearHeroes.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jb_villanos.setText("Crear Villano");
        jb_villanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_villanosMouseClicked(evt);
            }
        });
        jd_crearHeroes.getContentPane().add(jb_villanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jb_poder.setText("Crear Poder");
        jb_poder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_poderMouseClicked(evt);
            }
        });
        jd_crearHeroes.getContentPane().add(jb_poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_cate.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_cate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_cateMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_cate);

        jd_crearHeroes.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 215, 157));

        jButton3.setText("Actualizar Arbol");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jd_crearHeroes.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tree.png"))); // NOI18N
        jd_crearHeroes.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jl_villanos.setModel(new DefaultListModel());
        jl_villanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_villanosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_villanos);

        jd_crearHeroes.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, 170));

        jl_heroe.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_heroe);

        jd_crearHeroes.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 150, 170));

        jLabel15.setText("Villanos");
        jd_crearHeroes.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel16.setText("Heroes");
        jd_crearHeroes.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel17.setText("*El heroe debe tener al menos 1 poder para crearlo");
        jd_crearHeroes.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel18.setText("** El villano debe tener al menos 2 poderes para crearlo");
        jd_crearHeroes.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel19.setText("*");
        jd_crearHeroes.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 20, 20));

        jLabel20.setText("**");
        jd_crearHeroes.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));
        jd_crearHeroes.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jl_libres.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_libres);

        jl_encarcelados.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_encarcelados);

        javax.swing.GroupLayout jd_carcelLayout = new javax.swing.GroupLayout(jd_carcel.getContentPane());
        jd_carcel.getContentPane().setLayout(jd_carcelLayout);
        jd_carcelLayout.setHorizontalGroup(
            jd_carcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_carcelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jd_carcelLayout.setVerticalGroup(
            jd_carcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_carcelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jd_carcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jmi_mover.setText("Mover al Arbol");
        jmi_mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_moverActionPerformed(evt);
            }
        });
        jp_lista.add(jmi_mover);

        jmi_eliminar.setText("Eliminar");
        jp_lista.add(jmi_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Contraseña");
        jp_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));
        jp_login.add(tf_contraseñaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 230, 30));

        jb_iniciarSesion.setText("Iniciar Sesion");
        jb_iniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarSesionMouseClicked(evt);
            }
        });
        jp_login.add(jb_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        jLabel4.setText("Usuario");
        jp_login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));
        jp_login.add(tf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        jLabel1.setText("    ");
        jp_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_iniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarSesionMouseClicked
        // TODO add your handling code here:
        String c = "";
        String usuario = tf_usuario.getText();
        String contraseña = tf_contraseñaL.getText();

        if (usuarioP.equals(usuario) && contrasenaP.equals(contraseña)) {

            JOptionPane.showMessageDialog(this, "Se inició sesion con exito");
            c = JOptionPane.showInputDialog(this, "1) Crear persona \n 2) Carcel");

        } else {
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecta");

        }

        int opcion = Integer.parseInt(c);

        if (opcion == 1) {
            jd_crearHeroes.pack();
            jd_crearHeroes.setModal(true);
            jd_crearHeroes.setLocationRelativeTo(this);
            jd_crearHeroes.setVisible(true);
        } else if (opcion == 2) {
            jd_carcel.pack();
            jd_carcel.setModal(true);
            jd_carcel.setLocationRelativeTo(this);
            jd_carcel.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Esa opcion no existe");

        }
    }//GEN-LAST:event_jb_iniciarSesionMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (con != 0) {
            DefaultListModel modelo = (DefaultListModel) jl_heroe.getModel();
            String grupo = "";
            String o = JOptionPane.showInputDialog(this, "Elija el grupo: \n 1) Los Avengers \n 2) Los X-Men");
            int opcion = Integer.parseInt(o);

            switch (opcion) {
                case 1:
                    grupo = "Los Vengadores";
                    break;
                case 2:
                    grupo = "Los X-Men";
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "No existe esa opcion");
                    break;
            }

            modelo.addElement(new Superheroe(tf_nombre.getText(), (Integer) sp_edad.getValue(), tf_planeta.getText(), (Integer) sp_altura.getValue(), 0, grupo));

            jl_heroe.setModel(modelo);
            tf_nombre.setText("");
            sp_edad.setValue(15);
            tf_planeta.setText("");
            sp_altura.setValue(150);
            con = 0;
        } else if (con == 0) {
            JOptionPane.showMessageDialog(this, "No hay superpoderes creados");
        } else if (con == 4) {
            JOptionPane.showMessageDialog(this, "Ya tiene el limite de poderes");
        } else {
            JOptionPane.showMessageDialog(this, "No paso nada");

        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_villanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_villanosMouseClicked
        // TODO add your handling code here:

        if (con != 0 && con != 1) {
            String n;
            n = JOptionPane.showInputDialog(this, "Ingrese el numero de muertes causadas");
            int muertes = Integer.parseInt(n);

            DefaultListModel modelo = (DefaultListModel) jl_villanos.getModel();
            DefaultListModel modelo2 = (DefaultListModel) jl_libres.getModel();
            
            String grupo = "";
            String o = JOptionPane.showInputDialog(this, "Elija el grupo: \n 1) The Dark Avengers \n 2) The Sinister Six");
            int opcion = Integer.parseInt(o);

            switch (opcion) {
                case 1:
                    grupo = "The Dark Avengers";
                    break;
                case 2:
                    grupo = "The Sinister Six";
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "No existe esa opcion");
                    break;
            }

            Villanos villano = new Villanos(tf_nombre.getText(), (Integer) sp_edad.getValue(), tf_planeta.getText(), (Integer) sp_altura.getValue(), false, muertes, grupo);

            modelo.addElement(villano);
            modelo2.addElement(new Villanos(tf_nombre.getText(), (Integer) sp_edad.getValue(), tf_planeta.getText(), (Integer) sp_altura.getValue(), false, muertes, grupo));

            villano.setListaSuperpoder(listaPoderes);

            jl_villanos.setModel(modelo);
            jl_libres.setModel(modelo2);
            tf_nombre.setText("");
            sp_edad.setValue(15);
            tf_planeta.setText("");
            sp_altura.setValue(150);
            con = 0;
        } else if (con == 0) {
            JOptionPane.showMessageDialog(this, "No hay suficientes superpoderes creados");
        } else if (con == 4) {
            JOptionPane.showMessageDialog(this, "Ya tiene el limite de poderes");
        }


    }//GEN-LAST:event_jb_villanosMouseClicked

    private void jb_poderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_poderMouseClicked
        // TODO add your handling code here:
        listaPoderes = new ArrayList();

        boolean mortalidad = true;
        if (sp_mortal.getValue() == "Si") {
            mortalidad = true;
        } else if (sp_mortal.getValue() == "No") {
            mortalidad = false;
        } else {
            JOptionPane.showMessageDialog(this, "No hizo nada");
        }

        listaPoderes.add(new Superpoder((Integer) sp_nivel.getValue(), tf_descripcion.getText(), mortalidad));
        con++;
        JOptionPane.showMessageDialog(this, "Superpoder creado");

        tf_descripcion.setText("");
        sp_nivel.setValue(1);

    }//GEN-LAST:event_jb_poderMouseClicked

    private void jt_cateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cateMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jl_villanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_villanosMouseClicked
        // TODO add your handling code here:
        if (jl_villanos.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                jp_lista.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jl_villanosMouseClicked

    private void jmi_moverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_moverActionPerformed
        // TODO add your handling code here:

//        ((Villanos) modeloLISTA.get(jl_villanos.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("nombre"));
//
//        jl_personas.setModel(modeloLISTA);
//
//        if (jl_villanos.getSelectedIndex() >= 0) {
//            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_cate.getModel();
//
//            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
//            //obtener la persona a guardar
//            DefaultListModel modeloLISTA = (DefaultListModel) jl_villanos.getModel();
//
//            String nacionalidad, nombre;
//            int edad;
//            nacionalidad = ((Persona) modeloLISTA.get(jl_personas.getSelectedIndex())).getNacionalidad();
//
//            nombre = ((Persona) modeloLISTA.get(jl_personas.getSelectedIndex())).getNombre();
//
//            edad = ((Persona) modeloLISTA.get(jl_personas.getSelectedIndex())).getEdad();
//
//            int centinela = -1;
//            for (int i = 0; i < raiz.getChildCount(); i++) {
//                if (raiz.getChildAt(i).toString().equals(nacionalidad)) {
//
//                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Persona(nombre, edad, nacionalidad));
//
//                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
//                    centinela = 1;
//                } //fin if
//            } //fin for  
//
//            if (centinela == -1) {
//                DefaultMutableTreeNode n
//                        = new DefaultMutableTreeNode(nacionalidad);
//                DefaultMutableTreeNode p
//                        = new DefaultMutableTreeNode(
//                                new Persona(nombre, edad,
//                                        nacionalidad)
//                        );
//                n.add(p);
//                raiz.add(n);
//            }  // fin if          
//            modeloARBOL.reload();
//
//        } else {
//            JOptionPane.showMessageDialog(this,
//                    "No hay persona seleccionada");
//        }


    }//GEN-LAST:event_jmi_moverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mortalidad;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jb_iniciarSesion;
    private javax.swing.JButton jb_poder;
    private javax.swing.JButton jb_villanos;
    private javax.swing.JDialog jd_carcel;
    private javax.swing.JDialog jd_crearHeroes;
    private javax.swing.JList<String> jl_encarcelados;
    private javax.swing.JList<String> jl_heroe;
    private javax.swing.JList<String> jl_libres;
    private javax.swing.JList<String> jl_villanos;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_mover;
    private javax.swing.JPopupMenu jp_lista;
    private javax.swing.JPanel jp_login;
    private javax.swing.JTree jt_cate;
    private javax.swing.JSpinner sp_altura;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_mortal;
    private javax.swing.JSpinner sp_nivel;
    private javax.swing.JPasswordField tf_contraseñaL;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_planeta;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    String usuarioP = "Stan Lee", contrasenaP = "1234";
    int con;
    ArrayList<Superpoder> listaPoderes = new ArrayList();

}
